name: medical_calculator
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.2+4

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:
  flutter_dotenv: ^5.0.2
  flutter_signin_button: ^2.0.0
  email_validator: ^2.0.1
  fluttertoast: ^8.0.9
  dio: ^4.0.6
  url_launcher: ^6.1.4
  localstorage: ^4.0.0+1
  cupertino_icons: ^1.0.2
  google_sign_in: ^5.4.0
  uuid: ^3.0.6
  intl: ^0.17.0
  firebase_auth: ^3.6.1
  font_awesome_flutter: ^9.0.0
  provider: ^6.0.3
  firebase_core: ^1.20.0
  sign_in_with_apple: ^4.1.0

dev_dependencies:
  fluttericon: ^2.0.0
  
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Gangwon
      fonts:
        - asset: fonts/GangwonBold.ttf
        - asset: fonts/GangwonLight.ttf
          style: italic

  assets:
    - .env