// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeDtQEs1kcXbSRO4E_kCK25EW_9CAmbTM',
    appId: '1:939836489145:web:215fa19f666c1321210a68',
    messagingSenderId: '939836489145',
    projectId: 'medical-calculator-project',
    authDomain: 'medical-calculator-project.firebaseapp.com',
    storageBucket: 'medical-calculator-project.appspot.com',
    measurementId: 'G-VJJYYYHXY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqFUyC_ieJlbN0tBHWMMJEy7CByr7xRYA',
    appId: '1:939836489145:android:0e5ba0f04bbe28ab210a68',
    messagingSenderId: '939836489145',
    projectId: 'medical-calculator-project',
    storageBucket: 'medical-calculator-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaFTKE8kaph3iqXzOB8wJNr0f83yAkqIc',
    appId: '1:939836489145:ios:8c56dc3b21956e6b210a68',
    messagingSenderId: '939836489145',
    projectId: 'medical-calculator-project',
    storageBucket: 'medical-calculator-project.appspot.com',
    androidClientId: '939836489145-b9bf65rtoq4ljatv13e08nksjt5e18or.apps.googleusercontent.com',
    iosClientId: '939836489145-v781njshro569qj0vllfkavdog5de918.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicalCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaFTKE8kaph3iqXzOB8wJNr0f83yAkqIc',
    appId: '1:939836489145:ios:8c56dc3b21956e6b210a68',
    messagingSenderId: '939836489145',
    projectId: 'medical-calculator-project',
    storageBucket: 'medical-calculator-project.appspot.com',
    androidClientId: '939836489145-b9bf65rtoq4ljatv13e08nksjt5e18or.apps.googleusercontent.com',
    iosClientId: '939836489145-v781njshro569qj0vllfkavdog5de918.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicalCalculator',
  );
}
